### ISSUE TITLE
Crontab Sync Feeds 

### ISSUE THREAD

**Issue by ralphee** [kouya/snownews#40] opened 2020-01-21 20:34 UTC
Is there a way to sync all feeds in the background with crontab?

**Comment by kouya** [comment] 2020-01-22 12:49
Theoretically you could use something that inputs 'A', waits, then quits the program. But that will interfere with the running process. There is no native function for this. Since this is not a bug, but support request I am closing this.

**Closed by kouya** 2020-01-22 12:49 UTC
