### ISSUE TITLE
Youtube RSS feeds do not have links

### ISSUE THREAD

**Issue by kozross** [kouya/snownews#2] opened 2017-04-15 04:28 UTC
If I set up a Youtube RSS feed (through curl and atom2rss obviously), I end up with a feed that shows the titles of videos (and notifies me accordingly when new ones show up), but no links.

**Comment by kouya** [comment] 2017-04-15 09:48
Looks like the atom2rss converter doesn't pick up the link in Youtube's atom feed and therefore end up with an empty link tag in the RSS.

Unfortunately I know almost nothing about XSLT, so best guess is to contact the original author of the extension. Though from a look into the script it should correctly pick up the link tag in the atom feed.
https://kiza.eu/software/snownews/snowscripts/extensions/script/atom2rss/

Assuming you used that one.

Hm, with a bit of tinkering, if I remove "[@type='text/html']" from line 51 in the converter stylesheet

```
-		<link><xsl:value-of select="atom:link[@type='text/html']/@href" /></link>
+		<link><xsl:value-of select="atom:link/@href" /></link>
```
it does pick up the link tag. But that's really just shotgun debugging, unless that's ok for the purpose. ;)

Anyway, I'm closing this one since snownews itself doesn't support atom at all and the problem is with an extension.

**Closed by kouya** 2017-04-15 09:48 UTC

**Comment by kozross** [comment] 2017-04-15 10:32
Thanks, that worked like a charm! I'll contact the original author and ask them for a few iron-out tips.

**Comment by kianga** [comment] 2017-04-15 15:56
Here is an updated version of the script; it should work better with YouTube video feeds:

https://gist.github.com/kianga/dfae790d788005fe319d9dc6c7bda818
